version: "3.7"

services:
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    restart: always
    ports:
      - "2000:2000"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  user-auth:
    container_name: user-auth
    image: user-auth:latest
    restart: always
    ports:
      - "8084:8084"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  user-cmd-api:
    container_name: user-cmd-api
    image: user-cmd-api:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  user-query-api:
    container_name: user-query-api
    image: user-query-api:latest
    restart: always
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

networks:
  default:
    external:
      name: springNet